# docker-compose.yml
version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A app.celery_worker worker --loglevel=info

  celery_beat:
    build: .
    container_name: celery_beat
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A app.celery_worker beat --loglevel=info

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "5555:5555"
    environment:
      - FLOWER_BASIC_AUTH=username:password
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
